@echo off
REM Gradle wrapper batch script
REM This script is auto-generated by Android Gradle Plugin
REM Recommended: Use Android Studio UI for compilation

if not exist "gradle\wrapper\gradle-wrapper.jar" (
  echo Error: gradle-wrapper.jar not found
  exit /b 1
)

java -jar gradle\wrapper\gradle-wrapper.jar %*
